### ISSUE TITLE
Overlay created by GPX file extracted from the GoPro file is shorter than the original file

### ISSUE THREAD

**Issue by tuxinaut** [time4tea/gopro-dashboard-overlay#107]
Hello :wave: 

At fist thank you very much for this wounderful project :rocket: 

I'm pretty sure I'm doing something wrong but I do not see my mistake :disappointed: 

I wanted to create a overlay to use it in `Kdenlive` so I followed the documentation. I extracted the `GPX` from the original `GoPro` file and used it to create the overlay. It's **shorter** than the original `GoPro` file and has to the end not even data (the **last** three seconds).

Sorry for abusing an issue tracker for support :bowing_man: 

![gopro](https://user-images.githubusercontent.com/722482/218338404-1d9428b0-3261-42e1-b0f5-60c9f3631550.png)

**Comment by time4tea** [comment]
Hey! Thanks for your interest!

There are a lot of possibilities with the software. I was wondering if it might be easier to use `--generate overlay` with the original gopro file as input, rather than extract to gpx then use that to generate an overlay

Or, if you want to overlay the graphics, just use the software in default mode... it will generate the overlay directly from the gopro file.. no need for the intermediate gpx file.

Perhaps you had a specific reason for the gpx file? 

It is a bit tricky, there are so many ways to use the software, perhaps the current docs don't really make it obvious how to use.

**Comment by tuxinaut** [comment]
> There are a lot of possibilities with the software. I was wondering if it might be easier to use --generate overlay with the original gopro file as input, rather than extract to gpx then use that to generate an overlay

:facepalm: Yes this was exactly what I searched for! Not sure why I did not find it :shrug: 

> Perhaps you had a specific reason for the gpx file?

Nope, I thought for whichever reason that I have to follow [Create a movie with alpha channel, using only GPX file, without any video at all](https://github.com/time4tea/gopro-dashboard-overlay/tree/main/docs/bin#create-a-movie-with-alpha-channel-using-only-gpx-file-without-any-video-at-all), maybe it was way to late yesterday night :zzz: 

> It is a bit tricky, there are so many ways to use the software, perhaps the current docs don't really make it obvious how to use.

I'll check tomorrow, if it might make sense to _"simply"_ add that to the documentation/examples.

**Comment by time4tea** [comment]
hiya - did you get any further? - did the default mode work as expected. Please let me know if you encountered any other difficulties. Cheers!

**Comment by tuxinaut** [comment]
> hiya - did you get any further?

Yes everything worked as expected. The only catch was, that I had to use the overlay profile to get a transparent video.
