### ISSUE TITLE
Feature request: Add g-force/accelerometer

### ISSUE THREAD

**Issue by wedgeshot** [time4tea/gopro-dashboard-overlay#6]
Excellent project!!!    Can you add g-force/accelerometer overlay?

**Comment by time4tea** [comment]
Hiya. Thank you! Would you be able to give a few more details about the type of display that would be useful, and give some ideas about what kind of GPS traces you'd use this with. This would help inform how to implement this kind of feature.

**Comment by wedgeshot** [comment]
I think what you currently provide is great. I would like to see the g-forge/accelerometer above the MPH gauge/badge. Having command line option to not display maps or that temp/HR/RPM looks like you have in the works possibly.  I am using a GoPro Hero 9 currently,  mostly going to be recording Mountain Bike(mostly downhill sections), along with Motocross riding and possible race track days in my car.  I love everything on the overlay currently besides the bottom right badges as the GoPro does not provide that data. With that said, If I can figure out how to sync my Garmin Edge GPX data with the gopro "timing" the heart rate temp and RPM might work out later but not really all the important for me.  Thanks!

**Comment by wedgeshot** [comment]
Roger that.  With the weather now normal I'll have to start getting some recordings done with some forces enough to move "the needle" some. Thanks for the update.

**Comment by time4tea** [comment]
Just to let you know that this hasn't been forgotten. In fact as soon as #32 is sorted, this will be possible to implement, and *should* be relatively straightforward, as the hard work will have been done in order to fix that bug. The issue has been that the location/rotation data had all been stored by GPS time.. the changes are to store the info by video time, and will ensure that everything lines up.

**Comment by time4tea** [comment]
Acceleration parsing is released today in version 0.49.0
