### ISSUE TITLE
List index out of range error when Joining Files

### ISSUE THREAD

**Issue by YouthfulRicker** [time4tea/gopro-dashboard-overlay#87]
I tried to join 2 gopro recordings with this command:
~~~
~/venv/bin/gopro-join.py Documents/Driving\ Time\ Lapses/1.1-GX010092.MP4 Documents/Driving\ Time\ Lapses/1.2-GX020092.MP4 
~~~
And i got this error as a result:
~~~
Found: []
Traceback (most recent call last):
  File "/Users/antariksh/venv/bin/gopro-join.py", line 31, in <module>
    join_files(
  File "/Users/antariksh/venv/lib/python3.9/site-packages/gopro_overlay/ffmpeg.py", line 95, in join_files
    streams = find_streams(filepaths[0])
IndexError: list index out of range
~~~

**Comment by time4tea** [comment]
Thanks for raising this. I think I can see the issue. The problem is that the program didn't find any related files to join, and then doesn't check this before trying to join them.
The gopro-join expects that files will be named according to the gopro file naming convention, so it knows in which order to join them. You only need to give it one file, and it tries to "discover" the related files in the same folder. Your files are named "1.1..." - so it doesn't find them.

**Comment by YouthfulRicker** [comment]
Ok, so theoretically if I removed the decimal labelling convention it would work? I'll give this a go. Thanks!!
