### ISSUE TITLE
metric="gradient" no longer works since version 0.68.0

### ISSUE THREAD

**Issue by vilmic1** [time4tea/gopro-dashboard-overlay#91]
The last version where metric="gradient" works is version 0.67.0. Now instead of numbers, a dash is constantly displayed.
Although the working version of gradient wasn't perfect, I used it. Now I can't use it anymore. I would appreciate it if you could look into where the problem is.
Perhaps the performance could be improved, for example:
- link to speed, display only when the speed (MinSpeed) exceeds, for example, 5 km/h
- set MIN and MAX limits, for example: -20 and 20, when the values are displayed. Otherwise, a hyphen should be displayed instead of numbers.
- MinSpeed, MIN and MAX should be set in xml by configuring metric="gradient".
- it would be good to put the integration of the values in the program (long enough) so that the values changed slowly. Configurable value integration (averaging) should be implemented in all "metric" parameters, for example speed.

Thanks for the reply,
I wrote with "Google translate" :)
Vilmantas Michnevičius
Lithuania
vili@meganet.lt

**Comment by time4tea** [comment]
Hi - Thanks for your interest! - Yes - I very recently realised that this was broken. Sorry for that. I'm making some changes so that it should be fixed, and check that it won't get broken again.
It is a bit tricky to give a good gradient - as it is completely dependent on the location/altitude given from the GoPro - when this is inaccurate, so is the gradient. However, in the next release, I'm making some changes, so that gradient is limited to 45 degrees, and will only be calculated when there is a 3D lock.
I like the idea of a metric widget being able to configure the min & max displayed value.
I have tried various averaging techniques - including exponential smoothing, and Kalman filtering - unfortunately, the GPS inaccuracies last for a long time, and so they are not terribly useful - so far...

**Comment by time4tea** [comment]
This should be fixed (at least back to the previous behaviour) in version 0.78.0. Any issues, please let me know.

**Comment by vilmic1** [comment]
Thank you.
I tried it, everything works.
Vilmantas
